services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    expose:
      - "5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
      - N8N_HOST=35.219.118.133
      - N8N_PORT=443
      - WEBHOOK_URL=https://35.219.118.133
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - n8n
    restart: unless-stopped

volumes:
  n8n_data: