services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
      - N8N_PROTOCOL=https
      - N8N_HOST=35.219.118.133
      - N8N_PORT=5678
      - N8N_SSL_KEY=/certs/privkey.pem
      - N8N_SSL_CERT=/certs/fullchain.pem
    volumes:
      - ./certs:/certs:ro
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: